"""Criando tabela SolisConfig

Revision ID: 44bd6ce036ba
Revises: 2400f6df7ca8
Create Date: 2026-07-04 16:50:02.291040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44bd6ce036ba'
down_revision: Union[str, Sequence[str], None] = '2400f6df7ca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solis_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('api_url', sa.String(), nullable=False),
    sa.Column('key_id', sa.String(), nullable=False),
    sa.Column('key_secret', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id')
    )
    op.create_index(op.f('ix_solis_configs_id'), 'solis_configs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solis_configs_id'), table_name='solis_configs')
    op.drop_table('solis_configs')
    # ### end Alembic commands ###
